default_context:
  project_name: 'Ticker'
  project_slug: 'ticker'
  domain_main: 'ticker.com'
  domain_staging: 'stag.ticker.com'
  docker_swarm_stack_name_main: 'ticker-com'
  docker_swarm_stack_name_staging: 'stag-ticker-com'
  secret_key: '191e124f3d04a3bfec38f7ea37ee4be60ce928ccdc63b0f1cdca3203e46dd95d'
  first_superuser: 'kevin@ticker.com'
  first_superuser_password: '23031996'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ticker.com", "https://stag.ticker.com", "https://ticker.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ticker.com'
  postgres_password: '29f29d18d804891c867903010b3ac55e05850d5f2a8ae920a915533823281153'
  pgadmin_default_user: 'kevin@ticker.com'
  pgadmin_default_user_password: '23031996'
  traefik_constraint_tag: 'ticker.com'
  traefik_constraint_tag_staging: 'stag.ticker.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:23031996'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
