version: '2.0'
services:
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME}.app-db-data == true
  proxy:
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  app-db-data:
